# Generated by Django 4.1 on 2022-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contactno',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
