# Generated by Django 4.1 on 2022-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_id',
            field=models.EmailField(default=None, max_length=40, null=True),
        ),
    ]
