# Generated by Django 4.1 on 2022-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdb',
            name='refImg',
            field=models.ImageField(upload_to='reports/image/'),
        ),
    ]
