# Generated by Django 4.1 on 2022-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportdb_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdb',
            name='desc',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
