# Generated by Django 4.1 on 2022-09-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelongstoBusinnesnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to_business_unit', models.CharField(choices=[('FACTORY-UNIT', 'Factory-Unit'), ('CALLISTO-ELEMENT', 'Callisto-Element')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Mr.', 'MR.'), ('Mrs.', 'MRS.'), ('Shri', 'SHRI'), ('Shrimati', 'SHRIMATI')], max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cust_image', models.ImageField(upload_to='')),
                ('email_id', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=15)),
                ('building', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('belongstounit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.belongstobusinnesnit')),
            ],
        ),
    ]
