# Generated by Django 4.1 on 2022-09-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dated', models.DateTimeField(auto_now_add=True)),
                ('salutation', models.CharField(choices=[('Mr.', 'MR.'), ('Mrs.', 'MRS.'), ('Shri', 'SHRI'), ('Shrimati', 'SHRIMATI')], default=None, max_length=20, null=True)),
                ('name', models.CharField(default=None, max_length=30)),
                ('product', models.CharField(choices=[('WARDROBE-GST@18%', 'Wardrobe-GST@18%'), ('FURNITURE-GST@18%', 'Furniture-GST@18%'), ('KITCHEN-GST@18%', 'Kitchen-GST@18%'), ('DOOR-GST@18%', 'Door-GST%18%'), ('VANITY-GST@18%', 'Vanity-GST%18%'), ('PANELLING-GST@18%', 'Panelling-GST@18%'), ('SERVICE-GST@18%', 'Service-GST@18%'), ('ADDITIONAL-GST@18%', 'Additional-GST@18%')], default=None, max_length=100, null=True)),
                ('productDrNo', models.IntegerField()),
                ('reference', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('customerGST', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.IntegerField()),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
