# Generated by Django 4.1 on 2022-09-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_blockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockbtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(choices=[('WARDROBE-GST@18%', 'Wardrobe-GST@18%'), ('FURNITURE-GST@18%', 'Furniture-GST@18%'), ('KITCHEN-GST@18%', 'Kitchen-GST@18%'), ('DOOR-GST@18%', 'Door-GST@18%'), ('VANITY-GST@18%', 'Vanity-GST@18%'), ('PANELLING-GST@18%', 'Panelling-GST@18%'), ('SERVICE-GST@18%', 'Service-GST@18%'), ('ADDITIONAL-GST@18%', 'Additional-GST@18%')], default=None, max_length=70, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='desc',
            field=models.CharField(choices=[('WARDROBE-GST@18%', 'Wardrobe-GST@18%'), ('FURNITURE-GST@18%', 'Furniture-GST@18%'), ('KITCHEN-GST@18%', 'Kitchen-GST@18%'), ('DOOR-GST@18%', 'Door-GST@18%'), ('VANITY-GST@18%', 'Vanity-GST@18%'), ('PANELLING-GST@18%', 'Panelling-GST@18%'), ('SERVICE-GST@18%', 'Service-GST@18%'), ('ADDITIONAL-GST@18%', 'Additional-GST@18%')], default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='blockbtn_title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotations.blockbtn'),
        ),
    ]
