# Generated by Django 4.1 on 2022-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_blockbtn_alter_blockitem_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='blockbtn_title',
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='desc',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='payType',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='unit',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Blockbtn',
        ),
    ]
