# Generated by Django 4.1 on 2022-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_remove_blockitem_blockbtn_title_alter_blockitem_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=100, null=True)),
                ('desc', models.TextField()),
                ('unit', models.CharField(default=None, max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('payType', models.CharField(default=None, max_length=30, null=True)),
                ('img', models.ImageField(upload_to='applianceImg/Img/')),
            ],
        ),
        migrations.CreateModel(
            name='AppliancekDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=100, null=True)),
                ('desc', models.TextField()),
                ('unit', models.CharField(default=None, max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('payType', models.CharField(default=None, max_length=30, null=True)),
                ('img', models.ImageField(upload_to='FittingImg/Img/')),
            ],
        ),
        migrations.CreateModel(
            name='FittingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartage', models.IntegerField()),
                ('installation', models.IntegerField()),
                ('special_dis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WoodworkDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=30, null=True)),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='desc',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
