# Generated by Django 4.1 on 2022-10-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_appliance_appliancekdiscount_fitting_fittingdiscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliancekdiscount',
            old_name='percent',
            new_name='aPercent',
        ),
        migrations.RenameField(
            model_name='appliancekdiscount',
            old_name='type',
            new_name='aType',
        ),
        migrations.RenameField(
            model_name='appliancekdiscount',
            old_name='value',
            new_name='aValue',
        ),
        migrations.RenameField(
            model_name='fittingdiscount',
            old_name='percent',
            new_name='fPercent',
        ),
        migrations.RenameField(
            model_name='fittingdiscount',
            old_name='type',
            new_name='fType',
        ),
        migrations.RenameField(
            model_name='fittingdiscount',
            old_name='value',
            new_name='fValue',
        ),
        migrations.RenameField(
            model_name='packingdiscount',
            old_name='percent',
            new_name='pPercent',
        ),
        migrations.RenameField(
            model_name='packingdiscount',
            old_name='type',
            new_name='pType',
        ),
        migrations.RenameField(
            model_name='packingdiscount',
            old_name='value',
            new_name='pValue',
        ),
        migrations.RenameField(
            model_name='woodworkdiscount',
            old_name='percent',
            new_name='wPercent',
        ),
        migrations.RenameField(
            model_name='woodworkdiscount',
            old_name='type',
            new_name='wType',
        ),
        migrations.RenameField(
            model_name='woodworkdiscount',
            old_name='value',
            new_name='wValue',
        ),
    ]
